//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acumatica.DeviceHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acumatica.DeviceHub.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting job {0} from queue....
        /// </summary>
        internal static string DeletePrintJobNotify {
            get {
                return ResourceManager.GetString("DeletePrintJobNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the device to link to Acumatica for scale ID {0}..
        /// </summary>
        internal static string DeviceMissingPrompt {
            get {
                return ResourceManager.GetString("DeviceMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue is empty..
        /// </summary>
        internal static string EmptyQueueNotify {
            get {
                return ResourceManager.GetString("EmptyQueueNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - print job {1} has no &apos;FILEID&apos; parameter configured. The print job will be discarded..
        /// </summary>
        internal static string FileIdMissingWarning {
            get {
                return ResourceManager.GetString("FileIdMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your login..
        /// </summary>
        internal static string LoginMissingPrompt {
            get {
                return ResourceManager.GetString("LoginMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to {0}....
        /// </summary>
        internal static string LoginNotify {
            get {
                return ResourceManager.GetString("LoginNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out....
        /// </summary>
        internal static string LogoutNotify {
            get {
                return ResourceManager.GetString("LogoutNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is still running and monitoring your devices. To access it, click the icon in the tray..
        /// </summary>
        internal static string MinimizedToNotificationAreaWarning {
            get {
                return ResourceManager.GetString("MinimizedToNotificationAreaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Size {0} not found for printer {1}. Please verify configuration..
        /// </summary>
        internal static string PaperSizeMissingWarning {
            get {
                return ResourceManager.GetString("PaperSizeMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Source {0} not found for printer {1}. Please verify configuration..
        /// </summary>
        internal static string PaperSourceMissingWarning {
            get {
                return ResourceManager.GetString("PaperSourceMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string PasswordMissingPrompt {
            get {
                return ResourceManager.GetString("PasswordMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - print job {1} contains a file which doesn&apos;t look like a valid PDF file....
        /// </summary>
        internal static string PdfWrongFileFormatWarning {
            get {
                return ResourceManager.GetString("PdfWrongFileFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - print job {1} contains a PDF file that can&apos;t be sent in raw mode....
        /// </summary>
        internal static string PdfWrongModeWarning {
            get {
                return ResourceManager.GetString("PdfWrongModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while polling the print queue: {0}.
        /// </summary>
        internal static string PollingQueueUnknownError {
            get {
                return ResourceManager.GetString("PollingQueueUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling for new print jobs....
        /// </summary>
        internal static string PrintJobStartPollingNotify {
            get {
                return ResourceManager.GetString("PrintJobStartPollingNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - printing PDF to {1}....
        /// </summary>
        internal static string PrintPdfNotify {
            get {
                return ResourceManager.GetString("PrintPdfNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Queue {0} is not configured on this Acumatica instance. Please check configuration..
        /// </summary>
        internal static string PrintQueueConfigurationMissingWarning {
            get {
                return ResourceManager.GetString("PrintQueueConfigurationMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing print queues....
        /// </summary>
        internal static string PrintQueueInitializeNotify {
            get {
                return ResourceManager.GetString("PrintQueueInitializeNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Queue {0} initialized..
        /// </summary>
        internal static string PrintQueueInitializeSuccessNotify {
            get {
                return ResourceManager.GetString("PrintQueueInitializeSuccessNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please configure at least one print queue or scale to monitor..
        /// </summary>
        internal static string PrintQueueOrScaleConfigurationMissingPrompt {
            get {
                return ResourceManager.GetString("PrintQueueOrScaleConfigurationMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No print queues have been configured..
        /// </summary>
        internal static string PrintQueuesConfigurationMissingWarning {
            get {
                return ResourceManager.GetString("PrintQueuesConfigurationMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - printing raw data to {1}....
        /// </summary>
        internal static string PrintRawDataNotify {
            get {
                return ResourceManager.GetString("PrintRawDataNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue {0} - processing print job {1}....
        /// </summary>
        internal static string ProcessPrintJobNotify {
            get {
                return ResourceManager.GetString("ProcessPrintJobNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing print jobs in queue....
        /// </summary>
        internal static string ProcessPrintJobsNotify {
            get {
                return ResourceManager.GetString("ProcessPrintJobsNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give a name to this queue..
        /// </summary>
        internal static string QueueNameMissingPrompt {
            get {
                return ResourceManager.GetString("QueueNameMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scale configured..
        /// </summary>
        internal static string ScaleConfigurationMissingWarning {
            get {
                return ResourceManager.GetString("ScaleConfigurationMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to scale..
        /// </summary>
        internal static string ScaleConnectionError {
            get {
                return ResourceManager.GetString("ScaleConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the scale weight: {0}.
        /// </summary>
        internal static string ScaleWeightError {
            get {
                return ResourceManager.GetString("ScaleWeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale weight: {0}.
        /// </summary>
        internal static string ScaleWeightNotify {
            get {
                return ResourceManager.GetString("ScaleWeightNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to Acumatica: {0}.
        /// </summary>
        internal static string ScreenWebServiceConnexionError {
            get {
                return ResourceManager.GetString("ScreenWebServiceConnexionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting monitoring tasks....
        /// </summary>
        internal static string StartMonitoringNotify {
            get {
                return ResourceManager.GetString("StartMonitoringNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started successfully..
        /// </summary>
        internal static string StartMonitoringSuccessNotify {
            get {
                return ResourceManager.GetString("StartMonitoringSuccessNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping monitoring tasks....
        /// </summary>
        internal static string StopMonitoringNotify {
            get {
                return ResourceManager.GetString("StopMonitoringNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the monitoring tasks have been stopped..
        /// </summary>
        internal static string StopMonitoringSuccessNotify {
            get {
                return ResourceManager.GetString("StopMonitoringSuccessNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Device (VendorId=0x{0:X}, ProductId=0x{1:X}).
        /// </summary>
        internal static string UnknownDeviceDescription {
            get {
                return ResourceManager.GetString("UnknownDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating weight for scale ID {0}....
        /// </summary>
        internal static string UpdateScaleWeightNotify {
            get {
                return ResourceManager.GetString("UpdateScaleWeightNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight for scale ID {0} was updated..
        /// </summary>
        internal static string UpdateScaleWeightSuccessNotify {
            get {
                return ResourceManager.GetString("UpdateScaleWeightSuccessNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        internal static string UrlMissingPrompt {
            get {
                return ResourceManager.GetString("UrlMissingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing returned by webservice for report {0}.
        /// </summary>
        internal static string WebServiceReportReturnValueMissingWarning {
            get {
                return ResourceManager.GetString("WebServiceReportReturnValueMissingWarning", resourceCulture);
            }
        }
    }
}
